version: 2
docker_config:
  - &docker_config
      docker:
        - image: circleci/android:api-28-alpha
      working_directory: ~/repo
      environment:
        JAVA_OPTS: -Xmx1536m
        GRADLE_USER_HOME: /repo/.gradle
        TERM: dumb 

branch_config:
  - &branch_config
      branches:
        only:
          - develop      

jobs:
  build:
    <<: *docker_config
#    <<: *branch_config

    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle.kts" }}-{{ checksum "app/build.gradle.kts" }}
      - restore_cache:
          key: bundle-{{ checksum "Gemfile.lock" }}
      - run:
          name: Chmod permissions #if permission for Gradlew Dependencies fail, use this.
          command: sudo chmod +x ./gradlew
      - run:
          name: Bundle install
          command: bundle install --path vendor/bundle
      - save_cache:
          paths:
            - vendor/bundle
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle.kts" }}-{{ checksum "app/build.gradle.kts" }}
  ktlint:
    <<: *docker_config
#    <<: *branch_config
    steps:
      - checkout
      - run:
          name: Check
          command: |
              if [ ! $CIRCLE_BRANCH = 'master']; then
                  ./gradlew --stacktrace lint${APP_BUILD_TYPE^}
                  ./gradlew --stacktrace ktlint${APP_BUILD_TYPE^}Check
                  bundle exec danger
              fi
      - store_artifacts:
          path: app/build/reports
          destination: reports 
workflows:
  version: 2
  build-ktlint:
    jobs:
      - build
      - ktlint:
          requires:
            - build
          filters:
            branches:
              only: develop